question_data = [{"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "The Great Wall of China is visible from the moon.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "The color orange is named after the fruit.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "The mitochondria is the powerhouse of the cell.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "Pluto is a planet.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}
                 ]
